server:
  port: 8082

spring:
  application:
    name: user-service
  data:
    redis:
      host: localhost
      port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/medfund
    username: medfund
    password: medfund
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/medfund-platform

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

kafka:
  bootstrap-servers: localhost:9092

keycloak:
  admin:
    url: http://localhost:9080
    username: admin
    password: admin
  client:
    id: medfund-web   # OIDC client — embedded in Keycloak invite email links
