package com.medfund.finance.report.repository;

import com.medfund.finance.report.entity.ReportJob;
import com.medfund.finance.report.entity.ReportJobChunk;
import com.medfund.shared.testfixtures.AbstractPostgresIntegrationTest;
import io.r2dbc.postgresql.codec.Json;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.ReactiveJwtDecoder;
import org.springframework.test.context.TestPropertySource;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import java.time.Duration;
import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Phase 15 §3 chunk-row round-trip. Verifies:
 * <ul>
 *   <li>chunk row insert leaves the {@code chunk_id} generated by the DB
 *       (leave the {@code @Id} field null on insert per
 *       {@code bug_r2dbc_pre_populated_id_update_mode});</li>
 *   <li>the {@code parent_job_id} FK cascades on delete — deleting the
 *       parent {@code report_job} row removes its chunks in a single
 *       transaction;</li>
 *   <li>{@code findByParentJobId} and {@code findByParentJobIdAndStatus}
 *       return chunks scoped to the requested parent.</li>
 * </ul>
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@TestPropertySource(properties = {
        "spring.flyway.locations=classpath:db/test-migration",
        "spring.flyway.baseline-on-migrate=true",
        "report.retention.enabled=false"
})
@Import(ReportJobChunkIT.SecurityStub.class)
class ReportJobChunkIT extends AbstractPostgresIntegrationTest {

    private static final UUID TENANT = UUID.fromString("11111111-1111-1111-1111-111111111112");

    @Autowired private ReportJobChunkRepository chunkRepository;
    @Autowired private DatabaseClient client;

    @BeforeEach
    void clean() {
        // FK cascade takes chunk rows with the parent.
        client.sql("DELETE FROM report_job").fetch().rowsUpdated().block(Duration.ofSeconds(5));
    }

    @Test
    void insertChunk_generatesChunkId_andRoundtripsById() {
        UUID parent = insertParent("IFRS17_LRC_LIC_RECONCILIATION", ReportJob.RETENTION_STATUTORY_7Y);

        ReportJobChunk chunk = new ReportJobChunk();
        chunk.setParentJobId(parent);
        chunk.setPortfolioId(UUID.randomUUID());
        chunk.setCohortId(UUID.randomUUID());
        chunk.setCurrency("USD");
        chunk.setStatus("requested");
        chunk.setParamsJson(Json.of("{\"model\":\"PAA\"}"));
        chunk.setRequestedAt(OffsetDateTime.now(ZoneOffset.UTC));

        StepVerifier.create(chunkRepository.save(chunk)
                        .flatMap(saved -> chunkRepository.findById(saved.getChunkId())))
                .assertNext(fetched -> {
                    assertThat(fetched.getChunkId()).isNotNull();
                    assertThat(fetched.getParentJobId()).isEqualTo(parent);
                    assertThat(fetched.getCurrency()).isEqualTo("USD");
                    assertThat(fetched.getStatus()).isEqualTo("requested");
                    assertThat(fetched.getParamsJson().asString()).contains("\"PAA\"");
                })
                .verifyComplete();
    }

    @Test
    void parentDelete_cascadesChunkRows() {
        UUID parent = insertParent("IFRS17_INSURANCE_REVENUE_SERVICE_RESULT",
                ReportJob.RETENTION_STATUTORY_7Y);
        // Two chunks under the parent.
        chunkRepository.save(chunk(parent, "USD")).block(Duration.ofSeconds(5));
        chunkRepository.save(chunk(parent, "ZWL")).block(Duration.ofSeconds(5));

        assertThat(chunkRepository.findByParentJobId(parent).collectList().block(Duration.ofSeconds(5)))
                .hasSize(2);

        // Delete the parent — cascade should remove the chunks.
        client.sql("DELETE FROM report_job WHERE job_id = $1")
                .bind("$1", parent)
                .fetch().rowsUpdated().block(Duration.ofSeconds(5));

        assertThat(chunkRepository.findByParentJobId(parent).collectList().block(Duration.ofSeconds(5)))
                .as("chunks cascade-deleted with parent")
                .isEmpty();
    }

    @Test
    void findByParentJobIdAndStatus_filtersOnStatus() {
        UUID parent = insertParent("IFRS17_LRC_LIC_RECONCILIATION", ReportJob.RETENTION_STATUTORY_7Y);
        ReportJobChunk requested = chunk(parent, "USD");
        ReportJobChunk completed = chunk(parent, "ZWL");
        completed.setStatus("completed");
        completed.setCompletedAt(OffsetDateTime.now(ZoneOffset.UTC));

        chunkRepository.save(requested).block(Duration.ofSeconds(5));
        chunkRepository.save(completed).block(Duration.ofSeconds(5));

        assertThat(chunkRepository.findByParentJobIdAndStatus(parent, "requested")
                        .collectList().block(Duration.ofSeconds(5)))
                .hasSize(1)
                .allMatch(c -> "USD".equals(c.getCurrency()));
        assertThat(chunkRepository.findByParentJobIdAndStatus(parent, "completed")
                        .collectList().block(Duration.ofSeconds(5)))
                .hasSize(1)
                .allMatch(c -> "ZWL".equals(c.getCurrency()));
    }

    private UUID insertParent(String reportKey, String retentionClass) {
        UUID id = UUID.randomUUID();
        client.sql("""
                        INSERT INTO report_job (
                            job_id, tenant_id, report_key, status,
                            params_json, params_hash,
                            requested_at, requested_by_email, retention_class)
                        VALUES ($1, $2, $3, 'requested', '{}'::jsonb, $4, NOW(), 'test@example.test', $5)
                        """)
                .bind("$1", id)
                .bind("$2", TENANT)
                .bind("$3", reportKey)
                .bind("$4", id.toString().substring(0, 32))
                .bind("$5", retentionClass)
                .fetch().rowsUpdated().block(Duration.ofSeconds(5));
        return id;
    }

    private ReportJobChunk chunk(UUID parent, String currency) {
        ReportJobChunk c = new ReportJobChunk();
        c.setParentJobId(parent);
        c.setPortfolioId(UUID.randomUUID());
        c.setCohortId(UUID.randomUUID());
        c.setCurrency(currency);
        c.setStatus("requested");
        c.setParamsJson(Json.of("{}"));
        c.setRequestedAt(OffsetDateTime.ofInstant(Instant.now(), ZoneOffset.UTC));
        return c;
    }

    @TestConfiguration
    static class SecurityStub {
        @Bean
        ReactiveJwtDecoder reactiveJwtDecoder() {
            return token -> Mono.just(new Jwt(
                    token, Instant.now(), Instant.now().plusSeconds(300),
                    Map.of("alg", "none"),
                    Map.of("sub", "test", "iss", "test")));
        }
    }
}
